# Site settings
name: Kyle Gordy
email: kyle@kylegordydesign.com
description: "Passionate Designer & Front-end Developer with a love for learning and all things technology."

# Build settings
markdown: kramdown
permalink: pretty
highlights: false
